<?php

namespace Wizin\Bundle\SimpleCmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends EntityRepository
{
    /**
     * @param string $pathInfo
     * @return null|\Wizin\Bundle\SimpleCmsBundle\Entity\Content
     */
    public function retrieveEnableContent($pathInfo)
    {
        $criteria = [
            'pathInfo' => $pathInfo,
            'active' => true,
        ];

        return $this->findOneBy($criteria);
    }
}
