<?php

namespace Wizin\Bundle\SimpleCmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContentUpdateHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentUpdateHistoryRepository extends EntityRepository
{
}

